---
title: "Athletics Scraping"
author: "Emma Strawbridge"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidyr)
library(robotstxt)
library(stringr)
library(dplyr)
library(latex2exp)
library(RColorBrewer)
```

to do:
add readme
add tables at the end

```{r collect files}
# When this project was done, I did 22 (2022-2023) school year and 23 (2023-2024) school year. 
files_1 <- list.files(pattern = "1.txt", recursive = TRUE)
files_2 <- list.files(pattern = "2.txt", recursive = TRUE)
# This travel mileage document was just created in excel and saved as a csv
# For a different school it's going to be totally different
travel_distance <- read.csv("data/travel_mileage.csv", header = TRUE)

# dfmice = read.delim('/Users/estrawbridge/Desktop/amherst/SDS Fellows/SustainabilitySDSFellowProject/Athletics Emissions/data/mice23.txt', sep='\t', header = TRUE) 
# mice_num <- formatify(dfmice)
```


```{r}
data_framer <- function(file) {
  df <- read.delim(file, sep="\t", header = TRUE)
  # this first section formats the data so I can start changing the variables into what I need them to be
  tn <- word(df[1], start=2, end=3, sep=fixed(" "))
  team_name <- "dummy"
  team_name = case_when( 
      tn[1] == "Men's Ice" ~ "mice",
      tn[1] == "Women's Ice" ~ "wice", 
      tn[1] == "Baseball Schedule\"," ~ "baseball", 
      tn[1] == "Women's Basketball" ~ "wbball", 
      tn[1] == "Men's Basketball" ~ "mbball", 
      tn[1] == "Women's Cross" | tn == "Men's Cross" ~ "xc", # same schedule M/W at Amherst
      tn[1] == "Football Schedule\"," ~ "football", 
      tn[1] == "Women's Golf" ~ "wgolf", 
      tn[1] == "Men's Golf" ~ "mgolf", 
      tn[1] == "Women's Lacrosse" ~ "wlax", 
      tn[1] == "Men's Lacrosse" ~ "mlax", 
      tn[1] == "Women's Soccer" ~ "wsoc", 
      tn[1] == "Men's Soccer" ~ "msoc", 
      tn[1] == "Women's Squash" ~ "wsq", # same schedule M/W at Amherst, separate later
      tn[1] == "Men's Squash" ~ "msq", 
      tn[1] == "Women's Swimming" | tn == "Men's Swimming" ~ "sdt", # same schedule M/W at Amherst
      tn[1] == "Men's Tennis" ~ "mtennis", 
      tn[1] == "Women's Tennis" ~ "wtennis", 
      tn[1] == "Women's Track" | tn == "Men's Track" ~ "tf", # same schedule M/W at Amherst
      tn[1] == "Field Hockey" ~ "fhockey", 
      tn[1] == "Softball Schedule\"," ~ "softball",
      tn[1] == "Volleyball Schedule\"," ~ "vball",
      .default = "problem")
  # Some teams have different first rows going on, this removes the junk text
  if(team_name[1] == "xc") { 
     df <- df[-c(1:2), ]
  } else if(team_name[1] == "wgolf") {
     df <- df[-c(1:2), ]
  } else if(team_name[1] == "mgolf") {
     df <- df[-c(1:2), ]
  } else if(team_name[1] == "tf") {
     df <- df[-c(1:2), ]
  } else {
     df <- df[-c(1:8), ]
  }
  dfr <- data.frame(df) 
  
  # Second organization -- columns
  dfr <- dfr %>%
  rename(placeh = c(1)) %>% 
  # removes text that's getting in the way of reading information we need
  mutate(placeh = str_replace_all(placeh, ":", ""),
         placeh = str_replace_all(placeh, "(EST)", ""),
         placeh = str_replace_all(placeh, "(ET)", ""),
         placeh = str_replace_all(placeh, "/", ""),
         placeh = str_replace_all(placeh, "TBD", "TB D"),
         placeh = str_replace_all(placeh, "TBA", "TB A"),
         placeh = str_replace_all(placeh, " PM or ", "")) %>% 
  separate(placeh, c("A","B","C","D","E","F","G","H","I","J","K")) %>%
  select("A", "B", "F", "G", "H") %>%
  rename("month" = "A", 
         "day" = "B",   
         "h_a" = "F",
         "loc" = "G",
         "loc_2" = "H") %>% # 2nd parse for our repeats of "new" and "trinity" etc.
  mutate(game_n = as.numeric(rownames(dfr)),
         indicator = team_name[1]) %>%
  select(game_n, indicator, loc, loc_2, h_a) %>%
  left_join(travel_distance, join_by(loc, loc_2)) %>%
  mutate(
    # number of vehicles per sport -- this is an Amherst standard and will be different by institution
    n_veh = ifelse(h_a =="Away", 
         case_when(
         team_name == "tf" | team_name == "football" ~ 2,
         .default = 1),1), 
    # transportation type is also Amherst specific -- we are a bus school for the most part
    transp_type = ifelse(h_a =="Away",
                  case_when(
                  team_name == "wgolf" | team_name == "wtennis" | 
                  team_name == "mgolf" | team_name == "mtennis" ~ "van",
                  .default = "pete" # Peter Pan bus 
                  ), "none"),
    # the emissions for real! using EPA DATA, NOT SIMAP as of 10/6/24
    co_2gas = ifelse (h_a == "Away", case_when( # this is in kg also that's why I have *1000
                     transp_type == "van" ~ miles*523*n_veh*2/1000,
                     .default = miles*404*n_veh*2/1000 # Peter Pan bus
                     ), 0) 
         #driving 1 mile on average emits 404g of CO2 w/diesel (peter pan, sustainability office) 
         #driving 1 mile on average emits 523 of CO2 w/gas (van, epa and google) 
        
    ) %>%
    mutate(
    # trip population (in a separate mutate for my sake)
    pop_trip = case_when( #includes coaches except for football (formatted as athletes+coaches)
      team_name[1] == "mice" ~ 28+3,
      team_name[1] == "wice" ~ 22+3, 
      team_name[1] == "baseball" ~ 32+3, 
      team_name[1] == "wbball" ~ 13+1, 
      team_name[1] == "mbball"~ 15+3, 
      team_name[1] == "xc" ~ 23+21+2, 
      team_name[1] == "football" ~ 100, # +8 coaches who all drive, not included here
      team_name[1] == "wgolf" ~ 9+1,
      team_name[1] == "mgolf" ~ 11+1,
      team_name[1] == "wlax" ~ 33+3, 
      team_name[1] == "mlax" ~ 46+3, 
      team_name[1] == "wsoc" ~ 27+3, 
      team_name[1] == "msoc" ~ 35+4, 
      team_name[1] == "wsq" ~ 14+2,
      team_name[1] == "msq" ~ 16+2, 
      team_name[1] == "sdt" ~ 27+23+4, 
      team_name[1] == "mtennis" ~ 12+2, 
      team_name[1] == "wtennis" ~ 12+2, 
      team_name[1] == "tf" ~ 44+56+6, 
      team_name[1] == "fhockey" ~ 22+3, 
      team_name[1] == "softball" ~ 15+2,
      team_name[1] == "vball" ~ 21+2,
      .default = 0)
   ) %>% 
  mutate(co_2pcap = co_2gas/pop_trip,
         miles = as.double(miles))
  return(dfr)
}
```


```{r get all data together, warning=FALSE}
# for each year section
# this worked 20 minutes ago but now it doesn't
prep_1 <- sapply(files_1, data_framer)
prep_2 <- sapply(files_2, data_framer)

# first we set up the data frame
# getting the names for the columns
colnames <- rownames(prep_1)

# prepping the empty frame, and making it a global variable
emissions_1 <- data.frame(matrix(ncol = nrow(prep_1), nrow = 0))
colnames(emissions_1) <- colnames

emissions_2 <- data.frame(matrix(ncol = nrow(prep_2), nrow = 0))
colnames(emissions_2) <- colnames

# get each
create_emissions_1 <- function(col){
  hold_data <- as.data.frame(col)
  emissions_1 <- rbind(emissions_1,hold_data)
}

create_emissions_2 <- function(col){
  hold_data <- as.data.frame(col)
  emissions_2 <- rbind(emissions_2,hold_data)
}

# THIS here is what will run and collect all the data, run ONCE
emissions_1 <- apply(X = prep_1, MARGIN = 2, FUN = create_emissions_1)
emissions_1 <- bind_rows(emissions_1, .id = "column_label") %>%
               rename(source_file = column_label)

emissions_2 <- apply(X = prep_2, MARGIN = 2, FUN = create_emissions_2)
emissions_2 <- bind_rows(emissions_2, .id = "column_label") %>%
               rename(source_file = column_label)
```


```{r corrections by hand: year 2}
# There are a LOT of corrections by hand to do
# For Amherst athletics, this is our plane travel because that is not the norm here
# For your school that might look different -- refer back to the readme for more details

# Spring break trips
# We add these in manually, because there's only four
# and they're the same for each year! which is easy
source_file <- c("manual", "manual", "manual", "manual")
game_n <- c(0,0,0,0)
indicator <- c("baseball", "mbball", "sdt", "softball")
loc <- c("Florida", "Morocco", "PR", "Florida")
loc_2 <- c("Spring", "Quarter", "Spring", "Spring")
h_a <- c("Away", "Away", "Away", "Away")
miles <- c(1263, 3588, 1705, 1263)
n_veh <- c(1,1,1,1)
transp_type <- c("plane", "plane", "plane", "plane")
co_2gas <- c(164*35, (571/4)*18, 245*18, 164*17)
pop_trip <- c(35, 18, 18, 17)
co_2pcap <- c(0,0,0,0)

break_trips <- data.frame(source_file, game_n, indicator, loc, loc_2, h_a, miles, n_veh, transp_type, co_2gas, pop_trip, co_2pcap)

emissions_2 <- emissions_2 %>%
               rbind(break_trips) %>%
               # Remove repeat days for multiple day competitions/tournaments
               # We're not dealing with a large amount of data so this is somewhat hard-coded
               # One could definitely optimize this section, but I did not
               # They're in separate filter functions just because it's easier for me to read
               filter((indicator != "wgolf" & game_n != 2) | (indicator != "wgolf" & game_n != 4) |
                      (indicator != "wgolf" & game_n != 6) | (indicator != "wgolf" & game_n != 8) |
                      (indicator != "wgolf" & game_n != 11) | (indicator != "wgolf" & game_n != 12) |
                      (indicator != "wgolf" & game_n != 14) | (indicator != "wgolf" & game_n != 16) |
                      (indicator != "wgolf" & game_n != 18)) %>%
               filter((indicator != "mgolf" & game_n != 2) | (indicator != "mgolf" & game_n != 4) |
                      (indicator != "mgolf" & game_n != 6) | (indicator != "mgolf" & game_n != 8) |
                      (indicator != "mgolf" & game_n != 10) | (indicator != "mgolf" & game_n != 11) |
                      (indicator != "mgolf" & game_n != 13) | (indicator != "mgolf" & game_n != 15) |
                      (indicator != "mgolf" & game_n != 18)) %>%
               filter((indicator != "sdt" & game_n != 4) | (indicator != "sdt" & game_n != 11) |
                      (indicator != "sdt" & game_n != 12) | (indicator != "sdt" & game_n != 13) |
                      (indicator != "sdt" & game_n != 14) | (indicator != "sdt" & game_n != 16) |
                      (indicator != "sdt" & game_n != 17) | (indicator != "sdt" & game_n != 18)) %>%
               filter((indicator != "tf" & game_n != 3) | (indicator != "tf" & game_n != 4) |
                      (indicator != "tf" & game_n != 6) | (indicator != "tf" & game_n != 8) |
                      (indicator != "tf" & game_n != 13) | (indicator != "tf" & game_n != 17) |
                      (indicator != "tf" & game_n != 21)) %>%
              filter((indicator != "xc" & game_n != 2) | (indicator != "xc" & game_n != 3) |
                      (indicator != "xc" & game_n != 6) | (indicator != "xc" & game_n != 7))

# Hand-replacing stuff that got messed up/plane trips
# Pretty inefficient but whatever

# Women's Basketball
emissions_2[emissions_2$indicator == "wbball" & emissions_2$game_n == 8, 
            c(6, 7, 9, 10)] = c("Away", 1185, "plane", 211*14)
# Cross Country
emissions_2[emissions_2$indicator == "xc" & emissions_2$game_n == 2, 
            c(6, 7, 9, 10)] = c("Away", 66.9, "pete", 66.9*404*1*2/1000)
emissions_2[emissions_2$indicator == "xc" & emissions_2$game_n == 3, 
            c(6, 7, 9, 10)] = c("Away", 99.7, "pete", 99.7*404*1*2/1000)
emissions_2[emissions_2$indicator == "xc" & emissions_2$game_n == 7, 
            c(6, 7, 9, 10)] = c("Away", 371.5, "pete", 371.5*404*1*2/1000)
# Women's Golf
emissions_2[emissions_2$indicator == "wgolf" & emissions_2$game_n == 5, 
            c(6, 7, 9, 10)] = c("Away", 910, "plane", 192)
emissions_2[emissions_2$indicator == "wgolf" & emissions_2$game_n == 7, 
            c(6, 7, 9, 10)] = c("Away", 200, "van", 200*523*1*2/1000)
emissions_2[emissions_2$indicator == "wgolf" & emissions_2$game_n == 10, 
            c(6, 7, 9, 10)] = c("Away", 1050, "plane", 203*10) # Per person
emissions_2[emissions_2$indicator == "wgolf" & emissions_2$game_n == 13, 
            c(6, 7, 9, 10)] = c("Away", 257, "van", 257*523*1*2/1000)
emissions_2[emissions_2$indicator == "wgolf" & emissions_2$game_n == 17, 
            c(6, 7, 9, 10)] = c("Away", 61, "van", 61*523*1*2/1000)
# Men's Golf
emissions_2[emissions_2$indicator == "mgolf" & emissions_2$game_n == 9, 
            c(6, 7, 9, 10)] = c("Away", 1050, "plane", 203*12) # Per person
emissions_2[emissions_2$indicator == "mgolf" & emissions_2$game_n == 12, 
            c(6, 7, 9, 10)] = c("Away", 128, "van", 129*523*1*2/1000)
emissions_2[emissions_2$indicator == "mgolf" & emissions_2$game_n == 17, 
            c(6, 7, 9, 10)] = c("Away", 199, "van", 199*523*1*2/1000)
# Men's Lacrosse
emissions_2[emissions_2$indicator == "mlax" & emissions_2$game_n == 8, 
            c(6, 7, 9, 10)] = c("Away", 259, "pete", 259*404*1*2/1000)
# Women's Soccer
emissions_2[emissions_2$indicator == "wsoc" & emissions_2$game_n == 19, 
            c(6, 7, 9, 10)] = c("Away", 38, "pete", 38*404*1*2/1000)
# Men's Soccer
emissions_2[emissions_2$indicator == "msoc" & emissions_2$game_n == 17, 
            c(6, 7, 9, 10)] = c("Away", 85, "pete", 85*404*1*2/1000) # Per person
emissions_2[emissions_2$indicator == "msoc" & emissions_2$game_n == 19, 
            c(6, 7, 9, 10)] = c("Away", 57, "pete", 57*404*1*2/1000)
emissions_2[emissions_2$indicator == "msoc" & emissions_2$game_n == 23, 
            c(6, 7, 9, 10)] = c("Away", 1314, "plane", 182*39)
# Women's Squash
emissions_2[emissions_2$indicator == "wsq" & emissions_2$game_n == 17, 
            c(6, 7, 9, 10)] = c("Away", 260, "pete", 260*404*1*2/1000)
# Men's Squash
emissions_2[emissions_2$indicator == "msq" & emissions_2$game_n == 16, 
            c(6, 7, 9, 10)] = c("Away", 260, "pete", 260*404*1*2/1000)
# Swim & Dive
emissions_2[emissions_2$indicator == "sdt" & emissions_2$game_n == 10, 
            c(6, 7, 9, 10)] = c("Away", 85, "pete", 85*404*1*2/1000)
emissions_2[emissions_2$indicator == "sdt" & emissions_2$game_n == 25, 
            c(6, 7, 9, 10)] = c("Away", 207, "pete", 207*404*1*2/1000)
# Men's Tennis
emissions_2[emissions_2$indicator == "mtennis" & emissions_2$game_n == 1, 
            c(6, 7, 9, 10)] = c("Away", 88.9, "van", 88.9*523*1*2/1000)
emissions_2[emissions_2$indicator == "mtennis" & emissions_2$game_n == 2, 
            c(6, 7, 9, 10)] = c("Away", 200, "van", 200*523*1*2/1000)
emissions_2[emissions_2$indicator == "mtennis" & emissions_2$game_n == 8, 
            c(6, 7, 9, 10)] = c("Away", 1955, "plane", 251*14)
emissions_2[emissions_2$indicator == "mtennis" & emissions_2$game_n == 9, 
            c(6, 7, 9, 10)] = c("Neutral", 0, "none", 0)
emissions_2[emissions_2$indicator == "mtennis" & emissions_2$game_n == 11, 
            c(6, 7, 9, 10)] = c("Neutral", 0, "none", 0)
emissions_2[emissions_2$indicator == "mtennis" & emissions_2$game_n == 13, 
            c(6, 7, 9, 10)] = c("Neutral", 0, "none", 0)
# Women's Tennis
emissions_2[emissions_2$indicator == "wtennis" & emissions_2$game_n == 1, 
            c(6, 7, 9, 10)] = c("Away", 66.9, "van", 66.9*523*1*2/1000)
emissions_2[emissions_2$indicator == "wtennis" & emissions_2$game_n == 2, 
            c(6, 7, 9, 10)] = c("Away", 2888, "plane", 342*14)
emissions_2[emissions_2$indicator == "wtennis" & emissions_2$game_n == 8, 
            c(6, 7, 9, 10)] = c("Neutral", 0, "none", 0)
# Track & Field
emissions_2[emissions_2$indicator == "tf" & emissions_2$game_n == 1, 
            c(6, 7, 9, 10)] = c("Away", 66.9, "pete", 66.9*404*2*2/1000)
emissions_2[emissions_2$indicator == "tf" & emissions_2$game_n == 11, 
            c(6, 7, 9, 10)] = c("Away", 87.8, "pete", 7.8*404*2*2/1000)
emissions_2[emissions_2$indicator == "tf" & emissions_2$game_n == 12, 
            c(6, 7, 9, 10)] = c("Away", 87.8, "pete", 87.8*404*2*2/1000)
emissions_2[emissions_2$indicator == "tf" & emissions_2$game_n == 20, 
            c(6, 7, 9, 10)] = c("Away", 325.5, "pete", 325.5*404*2*2/1000)
emissions_2[emissions_2$indicator == "tf" & emissions_2$game_n == 23, 
            c(6, 7, 9, 10)] = c("Away", 87.7, "pete", 87.7*404*2*2/1000)
emissions_2[emissions_2$indicator == "tf" & emissions_2$game_n == 24, 
            c(6, 7, 9, 10)] = c("Away", 9.4, "pete", 9.4*404*2*2/1000)
emissions_2[emissions_2$indicator == "tf" & emissions_2$game_n == 25, 
            c(6, 7, 9, 10)] = c("neutral", 0, "none", 0)
emissions_2[emissions_2$indicator == "tf" & emissions_2$game_n == 27, 
            c(6, 7, 9, 10)] = c("Away", 823, "pete", 200*10)
```

```{r corrections by hand: year 1}
emissions_1 <- emissions_1 %>%
               rbind(break_trips) %>%
               # Remove repeat days for multiple day competitions/tournaments
               # We're not dealing with a large amount of data so this is somewhat hard-coded
               # One could definitely optimize this section, but I did not
               # They're in separate filter functions just because it's easier for me to read
               filter((indicator != "wgolf" & game_n != 2) | (indicator != "wgolf" & game_n != 4) |
                      (indicator != "wgolf" & game_n != 6) | (indicator != "wgolf" & game_n != 8) |
                      (indicator != "wgolf" & game_n != 10) | (indicator != "wgolf" & game_n != 12) |
                      (indicator != "wgolf" & game_n != 14) | (indicator != "wgolf" & game_n != 16) |
                      (indicator != "wgolf" & game_n != 18) | (indicator != "wgolf" & game_n != 19) |
                      (indicator != "wgolf" & game_n != 20)) %>%
               filter((indicator != "mgolf" & game_n != 2) | (indicator != "mgolf" & game_n != 4) |
                      (indicator != "mgolf" & game_n != 6) | (indicator != "mgolf" & game_n != 8) |
                      (indicator != "mgolf" & game_n != 10) | (indicator != "mgolf" & game_n != 12) |
                      (indicator != "mgolf" & game_n != 13) | (indicator != "mgolf" & game_n != 16) |
                      (indicator != "mgolf" & game_n != 18)) %>%
               filter((indicator != "sdt" & game_n != 10) | (indicator != "sdt" & game_n != 11) |
                      (indicator != "sdt" & game_n != 12) | (indicator != "sdt" & game_n != 14) |
                      (indicator != "sdt" & game_n != 15)) %>%
               filter((indicator != "tf" & game_n != 3) | (indicator != "tf" & game_n != 4) |
                      (indicator != "tf" & game_n != 7) | (indicator != "tf" & game_n != 11) |
                      (indicator != "tf" & game_n != 15) | (indicator != "tf" & game_n != 22) |
                      (indicator != "tf" & game_n != 24) | (indicator != "tf" & game_n != 27) |
                      (indicator != "tf" & game_n != 30))

# Hand-replacing stuff that got messed up/plane trips
# Pretty inefficient but whatever

# Women's Basketball
emissions_1[emissions_1$indicator == "wbball" & emissions_1$game_n == 8, 
            c(6, 7, 9, 10)] = c("Away", 2645, "plane", 330*14)

# Cross Country
emissions_1[emissions_1$indicator == "xc" & emissions_1$game_n == 5, 
            c(6, 7, 9, 10)] = c("Away", 205, "pete", 205*404*1*2/1000)
emissions_1[emissions_1$indicator == "xc" & emissions_1$game_n == 6, 
            c(6, 7, 9, 10)] = c("Away", 295.6, "pete", 295.6*404*1*2/1000)
emissions_1[emissions_1$indicator == "xc" & emissions_1$game_n == 7, 
            c(6, 7, 9, 10)] = c("Away", 709, "plane", 206*10)

# Women's Golf
emissions_1[emissions_1$indicator == "wgolf" & emissions_1$game_n == 9, 
            c(6, 7, 9, 10)] = c("Away", 166, "van", 166*523*1*2/1000)
emissions_1[emissions_1$indicator == "wgolf" & emissions_1$game_n == 15, 
            c(6, 7, 9, 10)] = c("Neutral", 0, "none", 0)
emissions_1[emissions_1$indicator == "wgolf" & emissions_1$game_n == 17, 
            c(6, 7, 9, 10)] = c("Away", 1252, "plane", 201*14) 
# Men's Golf
emissions_1[emissions_1$indicator == "mgolf" & emissions_1$game_n == 7, 
            c(6, 7, 9, 10)] = c("Away", 9.4, "van", 9.4*523*1*2/1000) 
emissions_1[emissions_1$indicator == "mgolf" & emissions_1$game_n == 9, 
            c(6, 7, 9, 10)] = c("Away", 170, "van", 170*523*1*2/1000)
emissions_1[emissions_1$indicator == "mgolf" & emissions_1$game_n == 12, 
            c(6, 7, 9, 10)] = c("Away", 128, "van", 129*523*1*2/1000)
emissions_1[emissions_1$indicator == "mgolf" & emissions_1$game_n == 15, 
            c(6, 7, 9, 10)] = c("Away", 200, "van", 200*523*1*2/1000)
emissions_1[emissions_1$indicator == "mgolf" & emissions_1$game_n == 17, 
            c(6, 7, 9, 10)] = c("Away", 1180, "plane", 154*14)
# Men's Lacrosse
emissions_1[emissions_1$indicator == "mlax" & emissions_1$game_n == 3, 
            c(6, 7, 9, 10)] = c("Away", 365, "pete", 365*404*1*2/1000)
emissions_1[emissions_1$indicator == "mlax" & emissions_1$game_n == 17, 
            c(6, 7, 9, 10)] = c("Away", 389, "pete", 389*404*1*2/1000)
# Women's Soccer
emissions_1[emissions_1$indicator == "wsoc" & emissions_1$game_n == 21, 
            c(6, 7, 9, 10)] = c("Away", 570, "plane", 201*30)
# Men's Soccer
emissions_1[emissions_1$indicator == "msoc" & emissions_1$game_n == 17, 
            c(6, 7, 9, 10)] = c("Away", 59.8, "pete", 59.8*404*1*2/1000)
# Women's Squash
emissions_1[emissions_1$indicator == "wsq" & emissions_1$game_n == 6, 
            c(6, 7, 9, 10)] = c("Away", 374, "pete", 74*404*1*2/1000)
emissions_1[emissions_1$indicator == "wsq" & emissions_1$game_n == 21, 
            c(6, 7, 9, 10)] = c("Away", 59.8, "pete", 59.8*404*1*2/1000)
# Men's Squash
emissions_1[emissions_1$indicator == "msq" & emissions_1$game_n == 17, 
            c(6, 7, 9, 10)] = c("Away", 52.8, "pete", 52.8*404*1*2/1000)
emissions_1[emissions_1$indicator == "msq" & emissions_1$game_n == 18, 
            c(6, 7, 9, 10)] = c("Away", 59.8, "pete", 59.8*404*1*2/10000)
# Swim & Dive
emissions_1[emissions_1$indicator == "sdt" & emissions_1$game_n == 9, 
            c(6, 7, 9, 10)] = c("Away", 207, "pete", 207*404*1*2/1000)
emissions_1[emissions_1$indicator == "sdt" & emissions_1$game_n == 13, 
            c(6, 7, 9, 10)] = c("Away", 699, "plane", 183*54)
# Men's Tennis
emissions_1[emissions_1$indicator == "mtennis" & emissions_1$game_n == 1, 
            c(6, 7, 9, 10)] = c("Away", 200, "van", 200*523*1*2/1000)
emissions_1[emissions_1$indicator == "mtennis" & emissions_1$game_n == 3, 
            c(6, 7, 9, 10)] = c("Away", 66.9, "van", 66.9*523*1*2/1000)
emissions_1[emissions_1$indicator == "mtennis" & emissions_1$game_n == 6, 
            c(6, 7, 9, 10)] = c("Away", 2880, "plane", 342*14)
# Women's Tennis
emissions_1[emissions_1$indicator == "wtennis" & emissions_1$game_n == 1, 
            c(6, 7, 9, 10)] = c("Away", 88.9, "van", 88.9*523*1*2/1000)
emissions_1[emissions_1$indicator == "wtennis" & emissions_1$game_n == 2, 
            c(6, 7, 9, 10)] = c("Away", 59.8, "van", 59.8*523*1*2/1000)
emissions_1[emissions_1$indicator == "wtennis" & emissions_1$game_n == 6, 
            c(6, 7, 9, 10)] = c("Away", 2880, "plane", 342*14)
emissions_1[emissions_1$indicator == "wtennis" & emissions_1$game_n == 18, 
            c(6, 7, 9, 10)] = c("Away", 85, "van", 85*523*1*2/1000)
emissions_1[emissions_1$indicator == "wtennis" & emissions_1$game_n == 7, 
            c(6, 7, 9, 10)] = c("Neutral", 0, "none", 0)
# Track & Field
emissions_1[emissions_1$indicator == "tf" & emissions_1$game_n == 1, 
            c(6, 7, 9, 10)] = c("Away", 66.9, "pete", 66.9*404*2*2/1000)
emissions_1[emissions_1$indicator == "tf" & emissions_1$game_n == 13, 
            c(6, 7, 9, 10)] = c("Away", 87.8, "pete", 87.8*404*2*2/1000)
emissions_1[emissions_1$indicator == "tf" & emissions_1$game_n == 21, 
            c(6, 7, 9, 10)] = c("Away", 99.7, "pete", 99.7*404*2*2/1000)
emissions_1[emissions_1$indicator == "tf" & emissions_1$game_n == 22, 
            c(6, 7, 9, 10)] = c("Away", 27.7, "pete", 27.7*404*2*2/1000)
emissions_1[emissions_1$indicator == "tf" & emissions_1$game_n == 23, 
            c(6, 7, 9, 10)] = c("Away", 91.3, "pete", 91.3*404*2*2/1000)
emissions_1[emissions_1$indicator == "tf" & emissions_1$game_n == 24, 
            c(6, 7, 9, 10)] = c("Away", 315.4, "pete", 315.4*404*2*2/1000)
emissions_1[emissions_1$indicator == "tf" & emissions_1$game_n == 26, 
            c(6, 7, 9, 10)] = c("Away", 9.4, "pete", 9.4*404*1*2/1000)
emissions_1[emissions_1$indicator == "tf" & emissions_1$game_n == 29, 
            c(6, 7, 9, 10)] = c("Away", 823, "plane", 200*10)
```

```{r total summary stats}
emissions_1 <- emissions_1 %>%
  mutate(yrcode = 1) %>%
  mutate(co_2gas = as.numeric(co_2gas)) %>%
  mutate(miles = as.numeric(miles))
emissions_2 <- emissions_2 %>%
  mutate(yrcode = 2) %>%
  mutate(co_2gas = as.numeric(co_2gas)) %>%
  mutate(miles = as.numeric(miles))
datam <- rbind(emissions_1, emissions_2)
sum1 <- sum(na.omit(emissions_1$co_2gas)) # 1st year total emissions
sum2 <- sum(na.omit(emissions_2$co_2gas)) # 2nd year total emissions
avg <- (sum1+sum2)/2 # two year average of athletic emissions

sum1
sum2
avg
```

```{r team grouped summary stats}
# total emissions by team
emissions_1_grp <- emissions_1 %>%
  group_by(indicator) %>% 
  summarise(co_2gas = sum(na.omit(as.numeric(co_2gas))))
emissions_1_grp

emissions_2_grp <- emissions_2 %>%
  group_by(indicator) %>% 
  summarise(co_2gas = sum(na.omit(as.numeric(co_2gas))))
emissions_2_grp

# total emissions by team per transp type
emissions_1_grp_t <- emissions_1 %>%
  group_by(indicator,transp_type) %>% 
  summarise(co_2gas = sum(na.omit(as.numeric(co_2gas))))
emissions_1_grp_t

emissions_2_grp_t <- emissions_2 %>%
  group_by(indicator,transp_type) %>% 
  summarise(co_2gas = sum(na.omit(as.numeric(co_2gas))))
emissions_2_grp_t

# two year average emissions by team
datamgrp <- datam %>%
  group_by(indicator) %>%
  summarise(co_2avg = sum(na.omit(as.numeric(co_2gas)))/2)
datamgrp
# average average yearly emissions by team
mean(datamgrp$co_2avg)

# team avg per game, including away games
datamgrp_gameav <- datam %>%
  filter(h_a == "Away") %>%
  group_by(indicator, h_a) %>%
  summarise(co_2avg_game = sum(na.omit(as.numeric(co_2gas))/length(h_a)))
datamgrp_gameav
mean(datamgrp_gameav$co_2avg_game)

# team avg per game, excluding away games
datamgrp_gameav_noaway <- datam %>%
  filter(h_a == "Away", transp_type != 'plane') %>%
  group_by(indicator, h_a) %>%
  summarise(co_2avg_game = sum(na.omit(as.numeric(co_2gas))/length(h_a)))
datamgrp_gameav_noaway
mean(datamgrp_gameav_noaway$co_2avg_game)

# two year average emissions by team by transp type
datamgrp2 <- datam %>%
  group_by(indicator,transp_type) %>%
  summarise(co_2avg = sum(na.omit(as.numeric(co_2gas)))/2)
datamgrp2

```

```{r viz}
datamgrp2no_none <- datamgrp2 %>%
  filter(transp_type != "none")

ggplot(datamgrp2no_none, aes(x=indicator, y=co_2avg, fill=indicator)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  guides(fill = guide_legend(title = "Team Indicator")) +
  xlab("Team Indicator") +
  ylab("kg CO2 Emitted per Season (two year average)") +
  ggtitle("kg CO2 Emitted per Season, by team, two year average")

ggplot(datamgrp2no_none, aes(x=indicator, y=co_2avg, fill=transp_type)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  guides(fill = guide_legend(title = "Transportation Type")) +
  scale_fill_brewer(palette="Set2") +
  xlab("Team Indicator") +
  ylab("kg CO2 Emitted per Season (two year average)") +
  ggtitle("kg CO2 Emitted per Season, by team, by transportation, two year average")

ggplot(datamgrp_gameav, aes(x=indicator, y=co_2avg_game, fill=indicator)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  guides(fill = guide_legend(title = "Team Indicator")) +
  xlab("Team Indicator") +
  ylab("Avaerage kg CO2 Emitted per game") +
  ggtitle("Average kg CO2 Emitted per game")

ggplot(datamgrp2no_none, aes(x="", y=co_2avg, fill=indicator)) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) +
  guides(fill = guide_legend(title = "transportation type"))

datamgrp2no_none <- datamgrp2 %>%
  filter(transp_type != "none")

ggplot(filter(datamgrp2no_none, transp_type!='plane'), aes(x=indicator, y=co_2avg, fill=indicator)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  guides(fill = guide_legend(title = "Team Indicator")) +
  xlab("Team Indicator") +
  ylab("kg CO2 Emitted per Season (two year average), no plane data") +
  ggtitle("kg CO2 Emitted per Season, by team, two year average")

ggplot(filter(datamgrp2no_none, transp_type!='plane'), aes(x=indicator, y=co_2avg, fill=transp_type)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  guides(fill = guide_legend(title = "Transportation Type")) +
  scale_fill_brewer(palette="Set2") +
  xlab("Team Indicator") +
  ylab("kg CO2 Emitted per Season (two year average), no plane data") +
  ggtitle("kg CO2 Emitted per Season, by team, by transportation, two year average")

ggplot(datamgrp_gameav_noaway, aes(x=indicator, y=co_2avg_game, fill=indicator)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  guides(fill = guide_legend(title = "Team Indicator")) +
  xlab("Team Indicator") +
  ylab("Avaerage kg CO2 Emitted per game, no plane data") +
  ggtitle("Average kg CO2 Emitted per game")
```

